spring:
  # Temporary H2 profile for local dev / quickstart
  h2:
    console:
      enabled: true
      path: /h2-console
  # QUICKSTART: in-memory H2
  datasource:
    url: jdbc:h2:mem:tasks;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none # use Flyway for schema
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

# Logging: keep it readable locally; switch to JSON in secure/prod profiles later
logging:
  level:
    root: INFO
    uk.gov.hmcts.tasks: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: when_authorized

# Idempotency backend selection:
# - default (absent or "jpa") uses the JPA-backed adapter
# - set to "redis" and configure redis.url to use Redis adapter
idempotency:
  backend: jpa

# Only required if idempotency.backend=redis
redis:
  url: redis://localhost:6379

---
# POSTGRES PROFILE (used by Docker Compose / Helm)
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: tasks
    password: tasks
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

# Example: enable Redis idempotency when running postgres profile under Compose/Helm
idempotency:
  backend: redis

# In Compose/Helm, the service name is "redis"
redis:
  url: redis://redis:6379
