services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tasks
      POSTGRES_PASSWORD: tasks
      POSTGRES_DB: tasks
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  api:
    build: ./api
    ports: ["8080:8080"]
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      idempotency.backend: redis
      redis.url: redis://redis:6379
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tasks
      SPRING_DATASOURCE_USERNAME: tasks
      SPRING_DATASOURCE_PASSWORD: tasks
    depends_on:
      - db
      - redis
