pipeline {
  agent any
  tools { jdk 'jdk21'; maven 'maven3' }
  stages {
    stage('Build & Test') {
      steps { sh 'mvn -q -B -f api/pom.xml clean verify' }
    }
    stage('Docker Build') {
      steps { sh 'docker build -t hmcts-api-service:local ./api' }
    }
  }
  post { always { junit 'api/target/surefire-reports/*.xml' } }
}
