name: ci
on:
  push:
    branches: [ main, master ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: api } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '21', cache: 'maven' }
      - name: Unit & BDD tests
        run: mvn -q -B clean verify
